{{- $backendProtocol := ternary "ssl" "tcp" (hasKey .Values.annotations.service "service.beta.kubernetes.io/aws-load-balancer-ssl-cert") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teleport-cluster.auth.labels" . | nindent 4 }}
{{/* TODO: annotations ? */}}
spec:
  ports:
  - name: auth
    port: 3025
    targetPort: 3025
    protocol: TCP
  selector: {{- include "teleport-cluster.auth.selectorLabels" . | nindent 4 }}
